head_yaw_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: head_yaw_joint

left_shoulder_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_shoulder_joint

left_arm_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_arm_joint

left_hand_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_hand_joint

left_waist_yaw_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_waist_yaw_joint

left_waist_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_waist_roll_joint

left_waist_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_waist_pitch_joint

left_knee_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_knee_pitch_joint

left_ankle_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_ankle_pitch_joint

left_ankle_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: left_ankle_roll_joint

right_shoulder_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_shoulder_joint

right_arm_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_arm_joint

right_hand_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_hand_joint

right_waist_yaw_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_waist_yaw_joint

right_waist_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_waist_roll_joint

right_waist_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_waist_pitch_joint

right_knee_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_knee_pitch_joint

right_ankle_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_ankle_pitch_joint

right_ankle_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: right_ankle_roll_joint
