head_controller:
  type: effort_controllers/JointTrajectoryController
  state_publish_rate: 10
  joints:
    - head_yaw_joint
  gains:
    head_yaw_joint: {p: 100.0, i: 0.01, d: 100.0}

left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  state_publish_rate: 10
  joints:
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_elbow_pitch_joint
  gains:
    left_shoulder_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_shoulder_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_elbow_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}

left_leg_controller:
  type: effort_controllers/JointTrajectoryController
  state_publish_rate: 10
  joints:
    - left_waist_yaw_joint
    - left_waist_roll_joint
    - left_waist_pitch_joint
    - left_knee_pitch_joint
    - left_ankle_pitch_joint
    - left_ankle_roll_joint
  gains:
    left_waist_yaw_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_waist_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_waist_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_knee_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_ankle_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
    left_ankle_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}

right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  state_publish_rate: 10
  joints:
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_elbow_pitch_joint
  gains:
    right_shoulder_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
    right_shoulder_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
    right_elbow_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
